spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=root
spring.datasource.password=ssssss
spring.datasource.url=jdbc:mysql://localhost:3306/BookStore
jwt.key=y84JIAb+cjmPyU3IYzq7QLBpUjhKZEUIyQc1jf9TgPSllpiy5DwWHfA4M8BRwmq2zo7wzeTc4bG2gv+ydS1CwMZt9HxVNu1I4u4+siXYMQhnUAI+AXReHlD6VK25EPACzICL/j5Z8VtwwvdmrKo9CujDVvs8ZVLfMzam6Gw1/DQ=
